### ISSUE TITLE
knp 格解析周りのパッチ

### ISSUE THREAD

**Issue by nakano-masahiro** [seiketkm/dockerfiles#1]
knp が時々 Segmentaion fault 起こす原因の１つを防ぐパッチです。
knp-4.19 ディレクトリで 下記コマンドを実行して適用してください。
`git apply パッチファイル名 `

$ cat knp_case_data.patch
```
diff --git a/system/case_data.c b/system/case_data.c
index 03eb6c9..ac9f8e8 100644
--- a/system/case_data.c
+++ b/system/case_data.c
@@ -593,8 +593,8 @@ int make_data_cframe_child(SENTENCE_DATA *sp, CF_PRED_MGR *cpm_ptr, TAG_DATA *ch
 
     for (child_num = 0; b_ptr->child[child_num]; child_num++);
 
-    /* 自分(用言)が複合名詞内 */
-    if (b_ptr->inum > 0) {
+    /* 自分(用言)が複合名詞内 */ /* 2018/08/15 Added parent check */
+    if (b_ptr->inum > 0 && b_ptr->parent) {
 	TAG_DATA *t_ptr;
 
 	/* 自分(用言)が複合名詞内のときの親 : 被連体修飾詞扱い
```

**Comment by seiketkm** [comment]
取り込みました！
git で作られたパッチファイルをgitで管理されてないとこで当てるには以下のコマンドを使うという知見を得ました。

`patch -p1 < knp_case_data.patch`

https://qiita.com/sea_mountain/items/7d9c812e68a26bd1a292

**Comment by seiketkm** [comment]
https://github.com/seiketkm/dockerfiles/blob/1.0.1/jumanpp_v2_knp/Dockerfile#L29

**Comment by nakano-masahiro** [comment]
git で管理されていないところでもできるのかと思っていました。

https://qiita.com/uasi/items/905376f02ff029fb23f8
